env:
  ImageOS: ubuntu18

name: Tests
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install development tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential libsodium-dev

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0 # Not needed with a .ruby-version file
        bundler-cache: false # runs 'bundle install' and caches installed gems automatically
    - run: gem install bundler:2.2.33 && bundle _2.2.33_ install && bundle install && bundle exec rspec spec/
